services:
  db:
    image: postgres:{{ cookiecutter.postgresql_version }}-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: "pg_isready --username=postgres && psql --username=postgres --list"
      timeout: 3s
      retries: 20

  web:
    build:
      context: .
      target: development
    restart: unless-stopped
    image: {{ cookiecutter.project_slug }}
    entrypoint: ["./entrypoints/run_server.sh"]
    volumes:
      - .:/opt/{{ cookiecutter.project_slug }}
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env

volumes:
  postgres_data:
